### ISSUE TITLE
Is stm32f405rgt6 a LQFP part?

### ISSUE THREAD

**Issue by MartinMcGrath** [pichenettes/eurorack#1]
Hi,

Thanks for making this available.

In the spreadsheet BOM for clouds, elements, rings and warps part stm32f405rgt6 is marked as having a TQFP64 package. I've done quite a few searches and can only find an LQFP64 part. Could this be a typo in the BOM or am I making a mistake?

Thanks again.

**Comment by pichenettes** [comment]
It's a typo.
