### ISSUE TITLE
Ripples v90 cad files missing

### ISSUE THREAD

**Issue by karshan** [pichenettes/eurorack#32]
I noticed that the schematic for the new ripples is available here: https://mutable-instruments.net/modules/ripples/downloads/ripples_v90.pdf

But I couldn't find the cad files in this repo. If this is intentional please ignore and close this issue.

Thanks a lot for your contribution to open source eurorack hardware!

**Comment by pichenettes** [comment]
CAD files are published when the development costs of a module have been recouped.
