### ISSUE TITLE
[Question] PCB viewer

### ISSUE THREAD

**Issue by deadeert** [pichenettes/eurorack#36]
Hello, 

I apologize for the beginner question, but what do you suggest to use to view PCB files (extensions are .brd and .sch)  ? 
I tried several tools but I did not manage to open these files.

If you have any suggestion concerning a free tool, I will be more than happy. 

Thanks you

**Comment by pichenettes** [comment]
Please ask on the forum: https://forum.mutable-instruments.net/.

This space is only to report bugs/issues with the codebase.

**Comment by deadeert** [comment]
I was not aware of such forum. Got my answer there.. 
Have a nice day.
