### ISSUE TITLE
A couple of variables are assigned values twice successively

### ISSUE THREAD

**Issue by SteveRussell33** [pichenettes/eurorack#53]
Found with static analysis.

``shifted_sample`` is assigned values twice successively.
https://github.com/pichenettes/eurorack/blob/db1566f68db7880baa569640e00f3854ab459adb/braids/macro_oscillator.cc#L116-L121

``previous_parameter_[0]`` is assigned values twice successively. 
https://github.com/pichenettes/eurorack/blob/db1566f68db7880baa569640e00f3854ab459adb/braids/digital_oscillator.cc#L744-L746

**Comment by pichenettes** [comment]
Commit clearing these will come soon.

The  shifted_sample += (parameter_[1] >> 2) + (parameter_[0] >> 4);  line is some dead code - I remember trying to mess with the DC offset before the waveshaper stage. But waveshaping an asymmetric waveform is nice too :D
