### ISSUE TITLE
braids decimation with envelope & AD_VCA

### ISSUE THREAD

**Issue by boochow** [pichenettes/eurorack#54]
Hello!  I am currently porting braids onto KORG drumlogue and have a question about this code

https://github.com/pichenettes/eurorack/blob/d1d8839c1147d8bf70c6012cf491be64aee66aa1/braids/braids.cc#L285-L288

When `decimation_factor` = n, the code multiplies `gain_lp` to `sample` n times, so the value of `sample` goes to `sample * pow(gain_lp, n)`, then when `(i % decimation_factor) == 0` becomes true, the new value is loaded from `render_buffer`.
Is this the intended behavior?
I mean, why the code wasn't like this?
```
    if ((i % decimation_factor) == 0) {
      sample = render_buffer[i] & bit_mask;
    }
    int16_t decimated_sample = sample * gain_lp >> 16;
```

**Comment by pichenettes** [comment]
You're right, this is a stupid bug and you can fix it.
