### ISSUE TITLE
various arrays intended as const are not, and so are consuming RAM

### ISSUE THREAD

**Issue by expertsleepers** [pichenettes/eurorack#55]
For example:

https://github.com/pichenettes/eurorack/blob/0232b4083f228fb12e0e59b657413b17a7e011ff/plaits/dsp/engine/chord_engine.cc#L86

would be better as

`int16_t const * const wavetable[] = {
`

**Comment by pichenettes** [comment]
Okay! Are there ones?

**Comment by expertsleepers** [comment]
Yes, quite a number of them. It's generally were an array of pointers is being declared.

`const <type>* variable = [] = {
`
You could probably grep them.

**Comment by pichenettes** [comment]
96 bytes of RAM saved!

Change to "resources_compiler.py" might break other projects - NOT TESTED FOR ANYTHING.

**Comment by lijon** [comment]
Just beware that RAM is faster than flash, so moving it away from RAM might affect performance.
