### ISSUE TITLE
Plaits - resources/waveterrains.py missing file ??

### ISSUE THREAD

**Issue by forestcaver** [pichenettes/eurorack#56]
Plaits - resources/waveterrains.py missing file ??

**Comment by pichenettes** [comment]
This is not needed, if there is a reference to this file somewhere (import) you can remove it. It is more efficient to compute the waveterrain function on the fly, as opposed to dedicating a heft amount of flash memory to it and doing a bilinear interpolation.

**Comment by forestcaver** [comment]
Thanks a lot - will remove !
