### ISSUE TITLE
Problems building Plaits Code

### ISSUE THREAD

**Issue by AlistairJohnsonG** [pichenettes/eurorack#57]
Hi,

I am using the published tool chain (https://pichenettes.github.io/mutable-instruments-documentation/modules/plaits/open_source/). I can successfully build code for Rings and Clouds but Plaits does not work.

I am able to build the bootloader for Plaits.

Here is the output from the "Cozy Development Environment":

vagrant@vagrant-ubuntu-trusty-64:/vagrant/eurorack-modules$ make -f plaits/makefile
stmlib/makefile.inc:373: build/plaits/depends.mk: No such file or directory
python stmlib/tools/resources_compiler.py plaits/resources/resources.py
Traceback (most recent call last):
  File "stmlib/tools/resources_compiler.py", line 280, in <module>
    main(sys.argv)
  File "stmlib/tools/resources_compiler.py", line 276, in main
    Compile(argv[i])
  File "stmlib/tools/resources_compiler.py", line 265, in Compile
    resource_module = __import__(base_name.replace('/', '.'))
  File "/vagrant/eurorack-modules/plaits/resources/resources.py", line 74, in <module>
    import waveterrains
ImportError: No module named waveterrains
make: *** [plaits/resources.cc] Error 1

Hopefully one of you kind "superstars" out there can help. Thanks in advance

Alistair

**Comment by pichenettes** [comment]
Remove the line ```import waveterrains``` in resources.py

**Comment by AlistairJohnsonG** [comment]
Hi,

Thanks for your very rapid help. 

Full respect to you and your work. I wish I had the time to learn what you did to create these fantastic products.

I can confirm that I removed "import waveterrains" in the resources.py file and have been able to build the code succesfully.

Again, many thanks
