### ISSUE TITLE
Inconsistent alt wave Aux envelope behaviour

### ISSUE THREAD

**Issue by bowlneudel** [pichenettes/eurorack#59]
With either Square or Sine Wave assigned to Aux output (any octave), and with Trig patched, certain modes output a continuous wave (expected behaviour — nice to have for sync or complementary gate sequencing), while others obey the VCA/VCFA envelope.

Is this by design, or a hold-over from how certain modes treat the stock Aux output?

Affected modes:
- G (All)
- R 1, 2, 3
- Y 1, 2, 6, 7

**Comment by pichenettes** [comment]
Please report this problem to the author of the alt firmware installed on your module. [Official firmware doesn't have assignable Aux.](https://github.com/lylepmills/eurorack)
